### PR TITLE
Fix sign up in Android

### LINKED ISSUE #2089: Cannot create new account.
On the sign up password page it displays "please select your country" and there is no country entry field, and it won't let you leave the page or continue through to create an account, there is no country selection field. 
screenshot_20180510-172605

### PR DESCRIPTION
**Pull request by juanlaube**
Closes #2089 

🦑 whenever

### CODE REVIEW

File: Toggl.Foundation.MvvmCross/ViewModels/LoginViewModel.cs [hunk 1]
```diff
@@ -346,16 +329,13 @@ private void googleLogin()
...
 
-                loginDisposable =
-                    loginManager
-                        .SignUp(Email, Password, TermsAccepted, CountryId.Value)
-                        .Do(_ => analyticsService.TrackSignUpEvent(AuthenticationMethod.EmailAndPassword))
-                        .Subscribe(onDataSource, onError, onCompleted);
-            }
+            loginDisposable =
+                loginManager
+                    .SignUp(Email, Password, true, null)
```
Comment (kornelijepetak) [inline Toggl.Foundation.MvvmCross/ViewModels/LoginViewModel.cs]: I would have this hard coded as well, but please do it thru constants. Much easier to change things later on.
