### PR TITLE
Fix device detection

### LINKED ISSUE #1441: Device type detection fails
The prefilled information in the feedbac email is incorrect. For my iPhone 7 it says “Failed to detect phone model”.

This might be possible to fix after i bit of a debugging, but I would suggest to include the model type onlywhen we can detect it and skip it if we can’t. It doesn’t look good...

### PR DESCRIPTION
**Pull request by simonrozsival**
Closes #1441 

Please make a functional test on a device

Squash whenever

### CODE REVIEW

File: Toggl.Foundation.MvvmCross/ViewModels/SettingsViewModel.cs [hunk 1]
```diff
@@ -171,13 +172,20 @@ await navigationService
             var version = userAgent.ToString();
             var phone = platformConstants.PhoneModel;
             var os = platformConstants.OperatingSystem;
-            //2 leading newlines, so user user can type something above this info
-            var message = $"\n\nVersion: {version}\nPhone: {phone}\nOS: {os}";
+
+            var messageBuilder = new StringBuilder();
+            messageBuilder.Append("\n\n"); // 2 leading newlines, so user user can type something above this info
```
Comment (willsb) [inline Toggl.Foundation.MvvmCross/ViewModels/SettingsViewModel.cs]: This is *very* OS specific. I don't really get the reason why you're doing it, but this should not be in the VM

Comment (simonrozsival) [reply Toggl.Foundation.MvvmCross/ViewModels/SettingsViewModel.cs]: I don't think that is within the scope of this PR. We should create an issue to refactor this in some future milestone.
