### PR TITLE
Sync failures views

### LINKED ISSUE #1334: UI to see projects/clients/tags that failed to sync
- [ ] We should try to show meaningful error messages, either those from backend or custom ones
- [ ] The user should be given a hint on how to resolve the issue (for example getting access back to a workspace)
- [ ] Users should be able to RETRY, DELETE(, RENAME?)
- In the future, if we allow projects/tags/clients to be edited, we may want to include the option to 'reset' the change by downloading the entity from backend

Overall, I think this screen should require the user to do a lot manually, but also give them the power to 'fix' their own syncing issues.

There are two different cases that should maybe be handled differently, in terms of what errors/hints to show:
- Actual sync of an entity failed
  - use backend error messages
- We find out that the user lost access to a workspace where they have unsynced entities
  - use custom error message
  - give hint about getting access back to workspace

### PR DESCRIPTION
**Pull request by Odrakir**
Closes #1334 

This probably still misses some stuff, but as it's going to work only for develop builds I say we start with this and work on it as needed.

### CODE REVIEW

File: Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs [hunk 1]
```diff
@@ -193,10 +198,16 @@ public void Init(string action)
                     RaisePropertyChanged(nameof(TimeEntriesCount));
                 });
 
+            var getNumberOfSyncFailuresDisposable = interactorFactory
+                .GetItemsThatFailedToSync().Execute()
+                .Select(i => i.Count())
+                .Subscribe(n => { NumberOfSyncFailures = n; });
```
Comment (simonrozsival) [inline Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs]: Please remove the curly braces, they are not needed.

File: Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs [hunk 2]
```diff
@@ -193,10 +198,16 @@ public void Init(string action)
                     RaisePropertyChanged(nameof(TimeEntriesCount));
                 });
 
+            var getNumberOfSyncFailuresDisposable = interactorFactory
+                .GetItemsThatFailedToSync().Execute()
```
Comment (simonrozsival) [inline Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs]: We put every method call on separate line in our codebase - so please break the line before the `.Execute()`.

File: Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs [hunk 3]
```diff
@@ -4,6 +4,7 @@
 using System.Linq;
 using System.Reactive.Linq;
 using System.Reactive.Subjects;
+using System.Runtime.CompilerServices;
```
Comment (simonrozsival) [inline Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs]: 👀

File: Toggl.Daneel/Views/SyncFailures/SyncFailureCell.cs [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+        }
+
+        public void Update(SyncFailureItem model)
+        {
+            typeLabel.Text = model.Type.ToString() + ": ";
+            nameLabel.Text = model.Name;
+            syncStatusLabel.Text = model.SyncStatus.ToString();
+            errorMessageLabel.Text = model.SyncErrorMessage;
+            switch (model.SyncStatus) {
+                case PrimeRadiant.SyncStatus.SyncFailed:
```
Comment (kornelijepetak) [inline Toggl.Daneel/Views/SyncFailures/SyncFailureCell.cs]: Use the `using` in that file:
```
namespace Toggl.Daneel.Views.SyncFailures
{
    using static Toggl.PrimeRadiant.SyncStatus;  // add this line
```

then just ditch the prefix and just do 

`case SyncNeeded:` and 
`case SyncFailed: `

File: Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs [hunk 5]
```diff
@@ -514,6 +525,29 @@ public sealed class TheCurrentTimeEntryClientProperty : CurrentTimeEntryproperty
...
         }
 
+        public sealed class TheNumberOfSyncFailuresProperty : MainViewModelTest
+        {
+            [Fact, LogIfTooSlow]
+            public async ThreadingTask ReturnsTheCountOfInteractorResult()
+            {
+                var syncables = new IDatabaseSyncable[]
+                {
+                    new MockTag { Name = "Tag", SyncStatus = SyncStatus.SyncFailed, LastSyncErrorMessage = "Error1" },
```
Comment (kornelijepetak) [inline Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs]: Another candidate for `using static SyncStatus`

File: Toggl.Daneel/ViewSources/ListTableViewSource.cs [hunk 6]
```diff
@@ -0,0 +1,34 @@
...
+using Foundation;
+using UIKit;
+
+namespace Toggl.Daneel.ViewSources
+{
+    public class ListTableViewSource<ModelType, CellType> : UITableViewSource where CellType : UITableViewCell
+    {
+        private readonly IList<ModelType> items;
+        private readonly string cellIdentifier;
+        private readonly Func<UITableViewCell, ModelType, CellType> configureCell;
```
[the remark this answers is not in the document]
Comment (Odrakir) [reply Toggl.Daneel/ViewSources/ListTableViewSource.cs]: Every time I see things like "handler" or "manager" in code I see someone having a hard time naming things. This is `configureCell` because that's exactly what this "method" (call it delegate or whatever) does. I could go as far as to call it `cellConfigurator`, but I find that using a noun makes the call feel less natural. I rather do `configureCell(whatever)` that `cellConfigurator(whatever)`

File: Toggl.Daneel/ViewSources/ListTableViewSource.cs [hunk 7]
```diff
@@ -0,0 +1,34 @@
...
+        }
+
+        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
+        {
+            var cell = tableView.DequeueReusableCell(cellIdentifier, indexPath);
+            var model = items[indexPath.Row];
+            return configureCell(cell, model);
+        }
+
+        public override nint RowsInSection(UITableView tableview, nint section)
```
[the remark this answers is not in the document]
Comment (Odrakir) [reply Toggl.Daneel/ViewSources/ListTableViewSource.cs]: WTF is EBM?

[the remark this answers is not in the document]
Comment (kornelijepetak) [reply Toggl.Daneel/ViewSources/ListTableViewSource.cs]: Expression-bodied member.
I gave an exact solution to my proposal.

File: Toggl.Daneel/ViewSources/ListTableViewSource.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (kornelijepetak) [reply Toggl.Daneel/ViewSources/ListTableViewSource.cs]: I agree with your reasoning. My proposal was to name the Type `CellConfigurationHandler`, but the parameter itself could be called `configureCell` to make the call more natural.
However, even if named with handler, every delegate can also be invoked like this:
`var cell = configureCellHandler.Invoke(cell, model);`

But like I said, it's not necessary to change this. This is a lose-lose scenario.

File: Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs (hunk 5 above)
Comment (Odrakir) [reply Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs]: I'm going to let this one be, just because we are already using `PrimeRadiant` and (though a little more verbose) I think it's a bit clearer this way.

File: Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs [hunk 8]
```diff
@@ -157,7 +159,7 @@ await NavigationService.Received()
 
                 var expected = isInManualMode ^ flipManualModeChecks
                     ? TimeSpan.FromMinutes(DefaultTimeEntryDurationForManualModeInMinutes)
-                    : (TimeSpan?)null;
+                    : (TimeSpan?) null;
```
Comment (simonrozsival) [inline Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs]: 👀

File: Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs [hunk 9]
```diff
@@ -532,9 +538,14 @@ public sealed class TheNumberOfSyncFailuresProperty : MainViewModelTest
             {
                 var syncables = new IDatabaseSyncable[]
                 {
-                    new MockTag { Name = "Tag", SyncStatus = SyncStatus.SyncFailed, LastSyncErrorMessage = "Error1" },
-                    new MockTag { Name = "Tag2", SyncStatus = SyncStatus.SyncFailed, LastSyncErrorMessage = "Error1" },
-                    new MockProject { Name = "Project", SyncStatus = SyncStatus.SyncFailed, LastSyncErrorMessage = "Error2" }
+                    new MockTag {Name = "Tag", SyncStatus = SyncStatus.SyncFailed, LastSyncErrorMessage = "Error1"},
+                    new MockTag {Name = "Tag2", SyncStatus = SyncStatus.SyncFailed, LastSyncErrorMessage = "Error1"},
```
Comment (simonrozsival) [inline Toggl.Foundation.Tests/MvvmCross/ViewModels/MainViewModelTests.cs]: 👀

File: Toggl.Daneel/Views/SyncFailures/SyncFailureCell.cs [hunk 10]
```diff
@@ -5,6 +5,8 @@
 
 namespace Toggl.Daneel.Views.SyncFailures
 {
+    using static Toggl.PrimeRadiant.SyncStatus;
```
Comment (kornelijepetak) [inline Toggl.Daneel/Views/SyncFailures/SyncFailureCell.cs]: Unfortunately, @amulware did not allow me to use static usings inside the namespace in my PR(yet), so I will assume the same principle applies to this as well. Just pull it before the namespace declaration, next to other usings.
