### PR TITLE
Stop crashes once and for all

### LINKED ISSUE #1523: Various GroupedCollectionTableViewSource crashes
There are multiple but similar types of crashes all occuring in `GroupedCollectionTableViewSource`:

**Example**: `NSInternalInconsistencyException: Invalid update: invalid number of rows in section 0. The number of rows contained in an existing section after the update (2) must be equal to the number of rows contained in that section before the update (2), plus or minus the number of rows inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).
`

  [📘 example of stack trace](https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/groups/b8d9705249f6cc94759d26d52829e190758c1597)

This happens with variable values. Numbers vary accross different errors (probably depending on the amount of user data).

### PR DESCRIPTION
**Pull request by willsb**
Closes #1523 AND LEAVES IT CLOSED

Test thoroughly and merge it when you feel like it

### CODE REVIEW

**Comment by amulware** [comment]
Requested two reviews. Others are VERY welcome.

File: Toggl.Foundation/DataSources/TimeEntriesDataSource.cs [hunk 1]
```diff
@@ -56,7 +56,7 @@ internal sealed class TimeEntriesDataSource : ITimeEntriesSource
             this.timeService = timeService;
             this.shortcutCreator = shortcutCreator;
 
-            TimeEntryCreated = timeEntryCreatedSubject.AsObservable();
+            TimeEntryCreated = timeEntryCreatedSubject.Select(TimeEntry.From).AsObservable();
```
Comment (simonrozsival) [inline Toggl.Foundation/DataSources/TimeEntriesDataSource.cs]: I don't think this is necessary - you already call this on every occasion where you call `OnNext` on this subject. Is there some reason I don't see?

File: Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs [hunk 2]
```diff
@@ -82,16 +83,18 @@ public sealed class TimeEntriesLogViewModel : MvxViewModel
...
             var updateDisposable =
                 dataSource.TimeEntries.TimeEntryUpdated
-                          .Subscribe(onTimeEntryUpdated);
+                    .Subscribe(onTimeEntryUpdated);
 
             var createDisposable =
                 dataSource.TimeEntries.TimeEntryCreated
                     .Where(isNotRunning)
-                    .Subscribe(safeInsertTimeEntry);
+                    .Buffer(TimeSpan.FromMilliseconds(500))
```
Comment (simonrozsival) [inline Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs]: Magic constant! And `500ms` is the final value? Wouldn't `100ms` or even less be enough?

File: Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs [hunk 3]
```diff
@@ -153,29 +156,39 @@ private void onTimeEntryUpdated((long Id, IDatabaseTimeEntry Entity) tuple)
                     return;
                 }
 
-                safeInsertTimeEntry(timeEntry);
+                safeInsertTimeEntries(new[] { timeEntry }.ToList());
             }
         }
 
-        private void safeInsertTimeEntry(IDatabaseTimeEntry timeEntry)
+        private void safeInsertTimeEntries(IList<IDatabaseTimeEntry> timeEntries)
```
Comment (simonrozsival) [inline Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs]: Wouldn't `IEnumerable` be enough? You enumerate it only once.. There wouldn't be a need for such an ugly conversion at line `159`.

**Comment by simonrozsival** [comment]
It seems to work fine so far.

File: Toggl.Foundation/DataSources/TimeEntriesDataSource.cs (hunk 1 above)
Comment (willsb) [reply Toggl.Foundation/DataSources/TimeEntriesDataSource.cs]: Nope, you are correct

File: Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs (hunk 2 above)
Comment (willsb) [reply Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs]: Reduced it to 100. Should be enough

File: Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs (hunk 3 above)
Comment (willsb) [reply Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs]: 👍

File: Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs [hunk 4]
```diff
@@ -21,6 +22,7 @@ namespace Toggl.Foundation.MvvmCross.ViewModels
     [Preserve(AllMembers = true)]
     public sealed class TimeEntriesLogViewModel : MvxViewModel
     {
+        private const int timeEntryCreationBuffer = 100;
```
[the remark this answers is not in the document]
Comment (amulware) [reply Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs]: I would prefer this being a timespan and having a name change as well.

File: Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs [hunk 5]
```diff
@@ -82,16 +84,18 @@ public sealed class TimeEntriesLogViewModel : MvxViewModel
...
                 dataSource.TimeEntries.TimeEntryUpdated
-                          .Subscribe(onTimeEntryUpdated);
+                    .Subscribe(onTimeEntryUpdated);
 
             var createDisposable =
                 dataSource.TimeEntries.TimeEntryCreated
                     .Where(isNotRunning)
-                    .Subscribe(safeInsertTimeEntry);
+                    .Buffer(TimeSpan.FromMilliseconds(timeEntryCreationBuffer))
+                    .DistinctUntilChanged()
```
Comment (amulware) [inline Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs]: Why the `DistinctUntilChanged`?

File: Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs [hunk 6]
```diff
@@ -82,16 +84,18 @@ public sealed class TimeEntriesLogViewModel : MvxViewModel
...
             var updateDisposable =
                 dataSource.TimeEntries.TimeEntryUpdated
-                          .Subscribe(onTimeEntryUpdated);
+                    .Subscribe(onTimeEntryUpdated);
 
             var createDisposable =
                 dataSource.TimeEntries.TimeEntryCreated
                     .Where(isNotRunning)
-                    .Subscribe(safeInsertTimeEntry);
+                    .Buffer(TimeSpan.FromMilliseconds(timeEntryCreationBuffer))
```
Comment (amulware) [inline Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs]: Does this lead to time entries showing up 100ms late after a sync/manual creation?

File: Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs [hunk 7]
```diff
@@ -153,29 +157,39 @@ private void onTimeEntryUpdated((long Id, IDatabaseTimeEntry Entity) tuple)
...
+                        TimeEntries.InsertInChildCollection(collectionIndex, timeEntryViewModel);
+                    }
+                }
+                else
+                {
+                    var timeEntriesToAdd = group.Select(te => new TimeEntryViewModel(te, durationFormat)).ToArray();
+                    var newCollection = new TimeEntryViewModelCollection(indexDate, timeEntriesToAdd, durationFormat);
+                    var foundIndex = TimeEntries.IndexOf(TimeEntries.FirstOrDefault(x => x.Date < indexDate));
+                    var indexToInsert = foundIndex == -1 ? TimeEntries.Count : foundIndex;
+                    TimeEntries.Insert(indexToInsert, newCollection);
```
Comment (amulware) [inline Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs]: I wouldn't mind having the two blocks here extracted as named methods for a bit better overview.

File: Toggl.Foundation/DataSources/TimeEntriesDataSource.cs [hunk 8]
```diff
@@ -135,12 +135,13 @@ public IObservable<IDatabaseTimeEntry> Create(IDatabaseTimeEntry entity)
             => repository
                 .UpdateWithConflictResolution(entity.Id, entity, alwaysCreate, rivalsResolver)
                 .Select(result => ((CreateResult<IDatabaseTimeEntry>)result).Entity)
+                .Select(TimeEntry.From)
```
Comment (amulware) [inline Toggl.Foundation/DataSources/TimeEntriesDataSource.cs]: Who dis?

Comment (amulware) [reply Toggl.Foundation/DataSources/TimeEntriesDataSource.cs]: Also all the ones below. Wrapping for thread safety because they come from realm? Is that necessary? (If so, why? Was this causing crashes?)

**Comment by amulware** [comment]
Two more questions:

1. I understand what the code does, but can you explain how this fixes the crash?
2. Why ~~500~~ 100ms?

File: Toggl.Foundation/DataSources/TimeEntriesDataSource.cs (hunk 8 above)
Comment (willsb) [reply Toggl.Foundation/DataSources/TimeEntriesDataSource.cs]: This starts causing crashes once we `Buffer` the time entries

Comment (amulware) [reply Toggl.Foundation/DataSources/TimeEntriesDataSource.cs]: Ah, the buffer causes it to escape the current thread since it's async, yes?

File: Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs (hunk 5 above)
Comment (willsb) [reply Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs]: 🔥

File: Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs (hunk 6 above)
Comment (willsb) [reply Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs]: Yes

**Comment by willsb** [comment]
It fixes the crash because we were sending two different add signals (one for adding sections and one for adding items) and before the section was animated the number of items would change again and that would explode. Now we add all the buffered items in bulk and all is well again.

100ms is enough time to buffer and get all the changes in the same batch that will update the UI

File: Toggl.Foundation/DataSources/TimeEntriesDataSource.cs (hunk 8 above)
Comment (amulware) [reply Toggl.Foundation/DataSources/TimeEntriesDataSource.cs]: Got that confirmed internally.

File: Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs [hunk 9]
```diff
@@ -153,30 +156,45 @@ private void onTimeEntryUpdated((long Id, IDatabaseTimeEntry Entity) tuple)
...
+                var indexDate = group.Key;
+                var collectionIndex = TimeEntries.IndexOf(x => x.Date.LocalDateTime == indexDate);
+                var groupExists = collectionIndex >= 0;
+                if (groupExists)
+                {
+                    foreach (var timeEntry in group)
+                    {
+                        var timeEntryViewModel = new TimeEntryViewModel(timeEntry, durationFormat);
+                        TimeEntries.InsertInChildCollection(collectionIndex, timeEntryViewModel);
+                    }
```
Comment (amulware) [inline Toggl.Foundation.MvvmCross/ViewModels/TimeEntriesLogViewModel.cs]: I'd like this loop in a method as well since it is on the same level as the method in the else block below unless you have a good reason why this should be here.

File: Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntriesLogViewModelTests.cs [hunk 10]
```diff
@@ -170,6 +171,7 @@ public sealed class WhenReceivingAnEventFromTheTimeEntryCreatedObservable : Time
                     await ViewModel.Initialize();
 
                     TimeEntryCreatedSubject.OnNext(NewTimeEntry);
+                    await ThreadingTask.Delay(200);
```
Comment (amulware) [inline Toggl.Foundation.Tests/MvvmCross/ViewModels/TimeEntriesLogViewModelTests.cs]: You made our tests last a whole second longer. :D
Should we refactor this to use a scheduler in a follow-up pr?

**Comment by amulware** [comment]
Oh, one more question: These changes are in shared code, for a pretty iOS specific bug. Are we ok with that?

**Comment by willsb** [comment]
Regarding both the possible refactor and the "solving iOS bugs in shared code":

This will all change in the future. Me and @simonrozsival are very much hating the current state of the StartTimeEntryViewModel. With Interactors coming, we'll eventually kill all of the DataSources, at which point the way we handle emission of updates will also change. So no, I don't think this will be a problem at all; this is bound to be refactored anyway.

**Comment by amulware** [comment]
Alright, that sounds good.
