### PR TITLE
Fixes for start time entry duration handling

### LINKED ISSUE #2061: Start TE View does not respect stopped time entries
Steps to reproduce:

* Start a new TE
* Click on a clock icon (to change the `Start and stop times`)
* Click on the `Stop` button as to stop the time entry.
* _The stop time shows correctly on the dialog_
* Click `Save`
* _User is returned to the start time entry_
* 🐛 _The duration is still going on at the top of the screen.
* 🗒 Note: The time entry **is** stopped, however. If you save the TE, it will be in the stopped mode, not still running.

Basically, only the UI should be changed to show that the time entry was stopped. Instead of duration, maybe display something like `06/14 16:22 - 16:28`. @pe0ny please advise 😄

### LINKED ISSUE #2115: Manual mode: duration is running on the popup
1) Turn on manual mode
2) Tap '+' to add a new entry
3) Tap on the duration -> Popup opens and you can see the timer is running
☝️ I think it doesn't affect the end result because when I save the entry, it save it with 30min duration, so it's only UI error?

### PR DESCRIPTION
**Pull request by willsb**
Closes #2061 
Closes #2115 
Ref #2096 and #2110 

Squash whenever

### CODE REVIEW

File: Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs [hunk 1]
```diff
@@ -127,6 +133,8 @@ public TimeSpan DisplayedTime
                 }
 
                 displayedTime = value;
+
+                RaisePropertyChanged();
```
Comment (kornelijepetak) [inline Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs]: Is this missing the `nameof(DisplayedTime)` or is this raising all of them... I've never seen this called parameterless. 😕

File: Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs [hunk 2]
```diff
@@ -458,6 +461,28 @@ private void clearTagsIfNeeded(long currentWorkspaceId, long newWorkspaceId)
...
 
+        private void OnDurationChanged()
+        {
+            if (Duration == null)
+            {
+                setUpTimeSubscriptionIfNeeded();
+                return;
+            }
+
+            DisplayedTime = Duration.Value;
```
Comment (kornelijepetak) [inline Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs]: This property `DisplayedTime` contains a timespan, I'd rather have this called `DisplayedDuration`. It really doesn't make sense that timespan is called `*Time`.

**Comment by kornelijepetak** [comment]
Also, note the failing test in bitrise. 😕

File: Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs (hunk 1 above)
Comment (willsb) [reply Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs]: You've never seen that because of Fody, that does the heavy lift for us.

This works because of [CallerMemberNameAttribute](
https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.callermembernameattribute(v=vs.110).aspx)

File: Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs (hunk 2 above)
Comment (willsb) [reply Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs]: Do you think this should be in this PR? Because the name was like that before

File: Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs (hunk 1 above)
Comment (kornelijepetak) [reply Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs]: So, we should use parameters only when it's needed to raise notifications for other members then, right?

File: Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs (hunk 2 above)
Comment (kornelijepetak) [reply Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs]: Make sense. I will add it to my `to refactor` list. And then when enough of those accumulate, I'll do a simple refactor PR.

File: Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs [hunk 3]
```diff
@@ -477,7 +477,7 @@ private void OnDurationChanged()
 
         private void setUpTimeSubscriptionIfNeeded()
         {
-            if (Duration == null || elapsedTimeDisposable != null) return;
+            if (Duration != null || elapsedTimeDisposable != null) return;
```
Comment (kornelijepetak) [inline Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs]: khm... I was looking at this expression and something looked wrong, but then I went around and explained it to myself some other way (wrongly obviously). 

Too tired I guess :)
