### PR TITLE
🚧 Fix Outdated Modal view crash

### LINKED ISSUE #3483: App Outdated showing crashes
## 🐛 Bug Report
When the app is outdated, the app tries to navigate to `OutdatedAppViewModel` then 💥

## Context

Build/Branch: `develop`
Phone OS: iOS
Phone model: Any

## Expected behavior
The outdated modal view should be shown.

## Stacktrace

```cs
System.NullReferenceException: Object reference not set to an instance of an object
  at Toggl.Daneel.Presentation.TogglPresenter.getPresentedViewController (UIKit.UIViewController current) [0x00000] in /Users/khoi/Documents/Workspaces/Repositories/toggl/mobileapp/Toggl.Daneel/Presentation/TogglPresenter.cs:249
  at Toggl.Daneel.Presentation.TogglPresenter.get_TopViewController () [0x00000] in /Users/khoi/Documents/Workspaces/Repositories/toggl/mobileapp/Toggl.Daneel/Presentation/TogglPresenter.cs:53
  at Toggl.Daneel.Presentation.TogglPresenter.showModalDialogViewController (System.Type viewType, MvvmCross.Presenters.Attributes.MvxBasePresentationAttribute attribute, MvvmCross.ViewModels.MvxViewModelRequest request) [0x00024] in /Users/khoi/Documents/Workspaces/Repositories/toggl/mobileapp/Toggl.Daneel/Presentation/TogglPresenter.cs:152
  at MvvmCross.Presenters.MvxAttributeViewPresenter.Show (MvvmCross.ViewModels.MvxViewModelRequest request) [0x00055] in <a6e263315c3e4a93a1b6bbd88bb441a4>:0
  at Toggl.Daneel.Presentation.TogglPresenter.Show (MvvmCross.ViewModels.MvxViewModelRequest request) [0x0004c] in /Users/khoi/Documents/Workspaces/Repositories/toggl/mobileapp/Toggl.Daneel/Presentation/TogglPresenter.cs:190
  at MvvmCross.Platforms.Ios.Views.MvxIosViewDispatcher+<>c__DisplayClass2_0.<ShowViewModel>b__0 () [0x0001d] in <a6e263315c3e4a93a1b6bbd88bb441a4>:0
  at MvvmCross.Base.MvxMainThreadAsyncDispatcher+<>c__DisplayClass0_0.<ExecuteOnMainThreadAsync>b__0 () [0x00000] in <a6e263315c3e4a93a1b6bbd88bb441a4>:0
  at MvvmCross.Base.MvxMainThreadAsyncDispatcher+<>c__DisplayClass1_0+<<ExecuteOnMainThreadAsync>b__0>d.MoveNext () [0x00011] in <a6e263315c3e4a93a1b6bbd88bb441a4>:0
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1018
  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/Foundation/NSAction.cs:178
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/UIKit/UIApplication.cs:79
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/UIKit/UIApplication.cs:63
  at Toggl.Daneel.Application.Main (System.String[] args) [0x00000] in /Users/khoi/Documents/Workspaces/Repositories/toggl/mobileapp/Toggl.Daneel/Startup/Main.cs:8
```

## To reproduce

Hard code to make the app outdated:

In `App.cs` add `|| true` to `NavigateToFirstViewModel`

```
if (true || accessRestrictionStorage.IsApiOutdated() || accessRestrictionStorage.IsClientOutdated())
```

### PR DESCRIPTION
**Pull request by khoi**
## What's this?
Fixes the crash when the app's outdated.

### Relationships
Closes #3483

## Why do we want this?
So we can notify users to update the app.

## How is it done?
The crash is caused because `TogglPresenter`'s `TopViewController` hasn't been set up properly in `App.cs` where the outdated check was.

I've changed the `OutdatedViewController` to `MvxRootPresentation` and add some adjustments to the view so it resembles a modal view. (see below)

### Why not another way?
This is a simple way.

### Side effects
Not that I know of.

## Review hints
In `App.cs` add `|| true` to `NavigateToFirstViewModel` to force an Outdated state

## :squid: Permissions
🐙

### CODE REVIEW

File: Toggl.Foundation.MvvmCross/App.cs [hunk 1]
```diff
@@ -53,13 +53,6 @@ protected override async void NavigateToFirstViewModel(object hint = null)
         {
             onboardingStorage.SetFirstOpened(timeService.CurrentDateTime);
 
-            if (accessRestrictionStorage.IsApiOutdated() || accessRestrictionStorage.IsClientOutdated())
```
Comment (simonrozsival) [inline Toggl.Foundation.MvvmCross/App.cs]: This code has to stay here. The check HAS to be performed before we check if the user is logged in or not.

**Comment by khoi** [comment]
I need some Mvx expertise on this one, the app crashes because of

https://github.com/toggl/mobileapp/blob/425c1a6cdf69862a2c80801f2c3f4c98c8db431b/Toggl.Daneel/Presentation/TogglPresenter.cs#L50

returns `null` at the moment when we `navigationService.Navigate<OutdatedAppViewModel>()`

https://github.com/toggl/mobileapp/blob/425c1a6cdf69862a2c80801f2c3f4c98c8db431b/Toggl.Foundation.MvvmCross/App.cs#L56-L61

File: Toggl.Daneel/Presentation/TogglPresenter.cs [hunk 2]
```diff
@@ -47,7 +47,7 @@ private UITabBarController mainTabBarController
             => mainViewController as UITabBarController;
 
         private UIViewController mainViewController
-            => UIApplication.SharedApplication.KeyWindow?.RootViewController;
+            => UIApplication.SharedApplication.KeyWindow?.RootViewController ?? _window.RootViewController;
```
Comment (simonrozsival) [inline Toggl.Daneel/Presentation/TogglPresenter.cs]: Wouldn't it be best to stick to `_window.RootViewController` all the time? 🤔

**Comment by khoi** [comment]
I made `OutdatedVC` a root screen, and have some tweak in the design (add background color, and some corner radius) and here is how it looks

screen shot 2018-11-07 at 11 51 28

Maybe we can go with this? @simonrozsival @willsb

File: Toggl.Daneel/Presentation/TogglPresenter.cs (hunk 2 above)
Comment (khoi) [reply Toggl.Daneel/Presentation/TogglPresenter.cs]: I'll revert the change to this since I feel like accessing internal `_window.RootViewController` is probably not a good idea.

**Comment by simonrozsival** [comment]
This doesn't really match the Zeplin design - the border radius should be greater (8pt) and the spider should hang from the top edge.
