### PR TITLE
Fix project and tag creation cells in start view

### LINKED ISSUE #4842: incorrect project creation cell text
## 🐛 Bug Report
project creation cell shows incorrect text

## Context
Build/Branch: `release/daneel-1.20-ifni`

## To reproduce
Create entry with the format:
`abc #tagb #tabod @udi`

image

## Expected behavior
The cell should shows `Create project "udi"`

### LINKED ISSUE #4843: incorrect tag creation cell text
## 🐛 Bug Report
tag creation cell shows incorrect text

## Context
Build/Branch: `release/daneel-1.20-ifni`

## To reproduce
Create entry with the format:
`abc #kd`

image

## Expected behavior
The cell should shows `Create tag "kd"`

### PR DESCRIPTION
**Pull request by arturs105**
## What's this?
This is PR #4680 again

### Relationships

Closes #4843
Closes #4842

## :squid: Permissions
🦑

### CODE REVIEW

File: Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs [hunk 1]
```diff
@@ -682,8 +682,9 @@ private IEnumerable<AutocompleteSuggestion> includeEmptyProject(AutocompleteSugg
                 {
                     sections = sections
                         .Prepend(
-                            SectionModel<string, AutocompleteSuggestion>.SingleElement(
-                                new CreateEntitySuggestion(Resources.CreateProject, textFieldInfo.Value.Description))
+                            CollectionSection<string, AutocompleteSuggestion>.SingleElement(
```
Comment (simonrozsival) [inline Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs]: Oh, you have to keep `SectionModel`, there's no `CollectionSection` anymore.
