### PR TITLE
Check for no-workspace in database

### LINKED ISSUE #2592: Change no-workspace detection to check database instead
Right now we check if the workspace endpoint returns any workspaces, but that won't be a good check in the future when we'll allow the situation where the user has a local unsynced workspace, and no remote ones.

The check should instead check the local database, and see if there are any workspaces there that are non-ghost, as will be defined in #1337

I believe the current handling of the situation which causes the sync machine to freeze and a special exception to be thrown does not have to change.

### PR DESCRIPTION
**Pull request by sofokli1**
Closes #2592

Checks database for workspaces after pulling and persisting workspaces from backend.

🦑 whenever

### CODE REVIEW

File: Toggl.Foundation/Sync/States/Pull/NoWorkspaceDetectingState.cs [hunk 1]
```diff
@@ -2,16 +2,24 @@
...
+        private readonly ITogglDataSource dataSource;
+
+        public NoWorkspaceDetectingState(ITogglDataSource dataSource)
+        {
+            this.dataSource = dataSource;
+        }
+
         public IObservable<ITransition> Start(IFetchObservables fetch)
-            => fetch.GetList<IWorkspace>()
+            => dataSource.Workspaces.GetAll()
```
Comment (juanlaube) [inline Toggl.Foundation/Sync/States/Pull/NoWorkspaceDetectingState.cs]: Should this select only workspaces that are in sync or in sync needed? 🤔 Ping @amulware

Comment (amulware) [reply Toggl.Foundation/Sync/States/Pull/NoWorkspaceDetectingState.cs]: This really depends on #1337. Right now those are the only two states that workspaces can be in, so I'd say this is fine as long as we remember to change it later according to what we do with #1337.
