### PR TITLE
Check for permission before reading calendar events

### LINKED ISSUE #3080: Check for permission before reading calendar events
In the [`BaseCalendarService`](https://github.com/toggl/mobileapp/blob/calendar-integration/Toggl.Foundation.MvvmCross/Services/BaseCalendarService.cs) we are checking for permissions (and throwing the adequate exceptions) before reading the user calendars.  We should do the same for the calendar events.

This change also requires changing the [interactor](https://github.com/toggl/mobileapp/blob/calendar-integration/Toggl.Foundation/Interactors/Calendar/GetCalendarItemsForDateInteractor.cs) to handle the error and return an empty list as the list of events so that everything works without permissions.

### PR DESCRIPTION
**Pull request by arturs105**
### Relationships

Closes #3080 

## :squid: Permissions
Whenever

### CODE REVIEW

File: Toggl.Foundation.MvvmCross/Services/BaseCalendarService.cs [hunk 1]
```diff
@@ -33,10 +34,31 @@ public IObservable<IEnumerable<UserCalendar>> GetUserCalendars()
...
+            {
+                var isAuthorized = permissionsService.CalendarPermissionGranted;
+                if (!isAuthorized)
+                {
+                    return Observable.Throw<IEnumerable<CalendarItem>>(
+                        new NotAuthorizedException("You don't have permission to access calendars")
+                    );
+                }
+
+                return Observable.Return(NativeTetEventsInRange(start, end));
```
Comment (sofokli1) [inline Toggl.Foundation.MvvmCross/Services/BaseCalendarService.cs]: what does `Tet` mean?
