### PR TITLE
Fix bugs in NoWorkspaceViewModel related to syncManager

### LINKED ISSUE #2769: Bugs in NoWorkspaceViewModel
## 🐛 Bug Report
Some bugs were discovered while testing the NoWorkspace UI.

- [x] `dataSource.User.Current` must call `FirstAsync()` otherwise it will never complete
- [ ] It doesn't sync the new workspace after creation. This seems simple, but it requires that a new `SyncManager` gets created and the old one gets disposed. The old one isn't usable because it has encountered an error (`NoWorkspaceException`) and is 💀.
- [ ] `TryAgain` method needs to be fixed. Due to the same SyncManager failure, a new one is required each time `TryAgain` is executed.
- [ ] When the issues are solved, the view presentation should be re-enabled in `ErrorHandlingService`.

To the person, who works on this: while you're at it, you might as well convert the view model's public methods to the new `RxAction`s (#2751).

## Expected behavior

No crashes 🙂

### PR DESCRIPTION
**Pull request by sofokli1**
## What's this?
Bug fixes to the `NoWorkspaceViewModel`. I am not addressing the part of the issue about `BindToAction` since i am not very familiar with it.

### Relationships

Closes #2769

## Why do we want this?
When the syncManager fails it is not usable anymore so we need to create a new one.

## How is it done?
It adds the to the `TogglDataSource` the ability to create a new sync manager. And this is used in the `NoWorkspaceViewModel`. It is quite tricky to test and reproduce for testing purposes. I myself am not 100% sure it works correctly. On the other hand I am not sure it is even needed since (at least from I see in the code) the sync manager is not frozen if no workspace exception is fired so in a way it should work without creating a new syncManager.

### Why not another way?

This is the only way I thought off.

### Side effects
Not sure. Either none or everything will break

## Review hints
I call on brave souls to try and test this in a functional way.
Would advise to try the steps from 
https://github.com/toggl/mobileapp/issues/2782#issuecomment-410079411
I myself am still trying to make this way to work

## :squid: Permissions
Whenever

### CODE REVIEW

File: Toggl.Foundation.MvvmCross/ViewModels/NoWorkspaceViewModel.cs [hunk 1]
```diff
@@ -35,6 +35,8 @@ public async Task TryAgain()
         {
             isLoading.OnNext(true);
 
+            dataSource.CreateNewSyncManager();
+
             var workspaces = await dataSource
```
Comment (juanlaube) [inline Toggl.Foundation.MvvmCross/ViewModels/NoWorkspaceViewModel.cs]: There's a crash when using `workspaces` related to accessing Realm from a different thread. It's easy to solve by adding the `.Any()` usage in this expression.

File: Toggl.Foundation.MvvmCross/ViewModels/NoWorkspaceViewModel.cs [hunk 2]
```diff
@@ -53,6 +55,8 @@ public async Task CreateWorkspaceWithDefaultName()
         {
             isLoading.OnNext(true);
 
+            dataSource.CreateNewSyncManager();
+
```
Comment (juanlaube) [inline Toggl.Foundation.MvvmCross/ViewModels/NoWorkspaceViewModel.cs]: You should kick a full sync after creating the workspace.

File: Toggl.Foundation/DataSources/TogglDataSource.cs [hunk 3]
```diff
@@ -90,12 +93,18 @@ public sealed class TogglDataSource : ITogglDataSource
...
+        public ISyncManager SyncManager { get; private set; }
 
         public IReportsProvider ReportsProvider { get; }
 
         public IFeedbackApi FeedbackApi { get; }
 
+        public void CreateNewSyncManager()
+        {
+            SyncManager = createSyncManager(this);
+            errorHandlingDisposable = SyncManager.ProgressObservable.Subscribe(onSyncError);
```
Comment (arturs105) [inline Toggl.Foundation/DataSources/TogglDataSource.cs]: Don't you need to dispose the previous disposable?

File: Toggl.Foundation.MvvmCross/ViewModels/NoWorkspaceViewModel.cs (hunk 1 above)
Comment (sofokli1) [reply Toggl.Foundation.MvvmCross/ViewModels/NoWorkspaceViewModel.cs]: @juanlaube isn't it used in line 48?

File: Toggl.Foundation/DataSources/TogglDataSource.cs (hunk 3 above)
Comment (sofokli1) [reply Toggl.Foundation/DataSources/TogglDataSource.cs]: @arturs105 take a look again when possible

**Comment by sofokli1** [comment]
@arturs105 and @juanlaube can i get some love here?

File: Toggl.Foundation.MvvmCross/ViewModels/NoWorkspaceViewModel.cs [hunk 4]
```diff
@@ -57,6 +57,10 @@ public async Task CreateWorkspaceWithDefaultName()
 
             dataSource.CreateNewSyncManager();
 
+            await dataSource
+                .SyncManager
+                .ForceFullSync();
+
```
Comment (juanlaube) [inline Toggl.Foundation.MvvmCross/ViewModels/NoWorkspaceViewModel.cs]: the ForceFullSync should be fired after creating the workspace.

Also, I've found another problem! 😅 But rejoice, because I may have the solution.
The default workspace id in the user profile still points to an old inaccessible workspace, we need to update that id.

Something like this should work...
```
var workspace = await dataSource.Workspaces.GetAll().FirstAsync().First();
user.DefaultWorkspaceId = workspace.Id;
await dataSource.User.Update(user);
```

Comment (simonrozsival) [reply Toggl.Foundation.MvvmCross/ViewModels/NoWorkspaceViewModel.cs]: Well that might be the same workspace as the default one. Also I don't think we should change the user's preferences. Maybe try using the `GetDefaultWorkspaceInteractor` + maybe add some validation into the interactor if we should filter inaccessible workspaces there.

Comment (sofokli1) [reply Toggl.Foundation.MvvmCross/ViewModels/NoWorkspaceViewModel.cs]: @juanlaube Line 70 is setting the default workspace for the user to the newly created.
@simonrozsival This is the wright place to set the default workspace (line 70) since the whole point of this code is for cases where the user does not have any workspace anywhere.

Comment (simonrozsival) [reply Toggl.Foundation.MvvmCross/ViewModels/NoWorkspaceViewModel.cs]: @sofokli1 you are right, I didn't get it the first time 👍
