### PR TITLE
Fix duration editing for running time entries

### LINKED ISSUE #447: Edit view duration editing
The user should be able to change the duration, which is translated into a change of the stop time strictly speaking. See #446

- [x] Fix the height glitch for long (>12h) time entries
- [ ] Fix duration editting for running time entries
- [x] Persist duration edits

### PR DESCRIPTION
**Pull request by arturs105**
Closes #447.

Editing running time entry used to set the stop time for the entry, making it not running anymore.

### CODE REVIEW

File: Toggl.Foundation.MvvmCross/ViewModels/EditDurationViewModel.cs [hunk 1]
```diff
@@ -62,7 +62,14 @@ private Task close()
             => navigationService.Close(this, defaultResult);
 
         private Task save()
-            => navigationService.Close(this, DurationParameter.WithStartAndStop(StartTime, StopTime));
+        {
+            DateTimeOffset? stopTimeToBeReturned;
+            if (isRunning)
```
Comment (willsb) [inline Toggl.Foundation.MvvmCross/ViewModels/EditDurationViewModel.cs]: Can't this benefit from using a ternary operator?

Comment (arturs105) [reply Toggl.Foundation.MvvmCross/ViewModels/EditDurationViewModel.cs]: Not very neatly, because of casting issues. The following would work, but i prefer an `if` over this:
```
var stopTime = isRunning ? null : (DateTimeOffset?)StopTime;
```
