### PR TITLE
Fix reports "This year" shortcut

### LINKED ISSUE #1245: Selecting "This year" in reports calendar makes the app crash
Reports calendar tries to mark the days of the whole year as selected - but it tries to mark also the days of months which are in the future and which aren't shown in our calendar and this incorrect indexing causes a crash.

### PR DESCRIPTION
**Pull request by simonrozsival**
Closes #1245, Ref #1211 

This PR fixes a 🐛 which was caused by invalid indexing. This code should be more declarative and easier to read. Also, there are now two property tests to ensure that the app won't crash.

Squash whenever

### CODE REVIEW

File: Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarDayViewModel.cs [hunk 1]
```diff
@@ -15,30 +22,27 @@ public sealed class CalendarDayViewModel : INotifyPropertyChanged
...
-        public DateTimeOffset ToDateTimeOffset()
-            => new DateTimeOffset(
-                CalendarMonth.Year,
-                CalendarMonth.Month,
-                Day,
-                0,
-                0,
-                0,
-                TimeSpan.Zero);
+        public DateTimeOffset ToDateTimeOffset() => dateTime;
```
Comment (arturs105) [inline Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarDayViewModel.cs]: This method could be changed to a property, since it's basically a getter now.
