### PR TITLE
✨ Inform users of account locking (security project part 2)

### LINKED ISSUE #7388: Detect the number of remaining login attempts on failed login attempts
## 🎯 What needs to be done?
Detect the number of remaining login attempts on failed login attempts.

## 📝 Detailed explanation
Use the header returned by backend `X-Remaining-Login-Attempts`. I'm not going to explain more, as I pretty much have a PR ready already (it sort of materialized when I was researching what needs to be done in this issue).

## 🏆 Outcome
In login view model, on failed login attempts, we know how many attempts are left.

## 👕 Estimated complexity
M

### LINKED ISSUE #7389: Let users know that their account is locked, or will be locked
## 🎯 What needs to be done?
Let users know that their account is locked, or will be locked.

## 📝 Detailed explanation
On failed login attempts, inspect the remaining attempts added in #7388. Then:
- if one attempt remains, display `Incorrect email or password. One more try before account gets locked for 5 minutes.` as the error message
- if 0 attempts remain, display `Incorrect email or password. Account is locked for 5 minutes. Account owner has been notified.` as the error message.

Display the messages in accordance with UX described here https://www.notion.so/toggl/UX-documentation-for-account-locking-done-5f507305dd3048d7ac9da9930612b9be. Most relevant part is: `Error text should push the "Forgot password?" & CTA down so 3 lines of error text would fit`
and `iOS error text in dark mode should be red and not white`

## 🏆 Outcome
Remaining attempts:
- `>1`: regular error message displayed
- ==1: one more try message displayed
- ==0: account locked message displayed
- UX is as designed

## 👕 Estimated complexity
S

### LINKED ISSUE #7390: Let users know that their account is locked, or will be locked
## 🎯 What needs to be done?
Let users know that their account is locked, or will be locked.

## 📝 Detailed explanation
On failed login attempts, inspect the remaining attempts added in #7388. Then:
- if one attempt remains, display `Incorrect email or password. One more try before account gets locked for 5 minutes.` as the error message
- if 0 attempts remain, display `Incorrect email or password. Account is locked for 5 minutes. Account owner has been notified.` as the error message.

Display the messages in accordance with UX described here https://www.notion.so/toggl/UX-documentation-for-account-locking-done-5f507305dd3048d7ac9da9930612b9be. Most relevant part is: `Error text should push the "Forgot password?" & CTA down so 3 lines of error text would fit`.

## 🏆 Outcome
Remaining attempts:
- >1: regular error message displayed
- ==1: one more try message displayed
- ==0: account locked message displayed
- UX is as designed

## 👕 Estimated complexity
S

### LINKED ISSUE #7391: Make the login error text red in dark mode
## 🎯 What needs to be done?
Make the login error text red in dark mode.

## 🏆 Outcome
iPhone in dark mode, try to login with a wrong password. Result: the error text is red, not white as it currently is.

## 👕 Estimated complexity
S

### PR DESCRIPTION
**Pull request by pdrj**
## What's this?
This:
- reads the remaining login attempts header from backend responses
- informs users about the remaining attempts, as per UX design https://www.notion.so/toggl/UX-documentation-for-account-locking-done-5f507305dd3048d7ac9da9930612b9be
- does some UI changes to make sure error message always fits

### Relationships

Closes #7391 
Closes #7390 
Closes #7388 
Closes #7389 

## Why do we want this?
Because security

### Why not another way?
Open to suggestions.

### Side effects
Shouldn't be any, I hope.

## Review hints
Code should be nicely reviewable commit-by-commit. 

Functionally, on staging try to login 10 times with a wrong password and see if the error changes accordingly and is displayed properly.

Also, make sure you can actually login.  

## Tests
When backend deploys the changes for good, it'd be nice to add an integration test for the remaining attempts.

## :squid: Permissions
Anyone

### CODE REVIEW

File: Toggl.Networking/Exceptions/UnauthorizedException.cs [hunk 1]
```diff
@@ -30,6 +34,24 @@ internal UnauthorizedException(IRequest request, IResponse response, string erro
...
         {
             requestHeaders = request.Headers;
+            RemainingLoginAttempts = getRemainingLoginAttemptsFromHeaders(response.Headers);
+        }
+
+        private int getRemainingLoginAttemptsFromHeaders(HttpHeaders headers)
+        {
+            if (headers == null)
+            {
+                return -1;
```
Comment (heytherewill) [inline Toggl.Networking/Exceptions/UnauthorizedException.cs:44]: Why -1 and not null?

File: Toggl.Networking/ApiClients/BaseApi.cs [hunk 2]
```diff
@@ -84,6 +82,21 @@ protected async Task<T> SendRequest<T>(Endpoint endpoint, IEnumerable<HttpHeader
                 : default(T);
         }
 
+        protected virtual async Task<Exception> getExceptionFor(IRequest request, IResponse response, IEnumerable<HttpHeader> headers)
```
Comment (heytherewill) [inline Toggl.Networking/ApiClients/BaseApi.cs:85]: Protected stuff should be `PascalCase`

File: Toggl.Networking/ApiClients/UserApi.cs [hunk 3]
```diff
@@ -17,6 +19,8 @@ namespace Toggl.Networking.ApiClients
 {
     internal sealed class UserApi : BaseApi, IUserApi
     {
+
+
```
Comment (heytherewill) [inline Toggl.Networking/ApiClients/UserApi.cs:23]: Extraneous white space

File: Toggl.Networking/Exceptions/UnauthorizedException.cs (hunk 1 above)
Comment (pdrj) [reply Toggl.Networking/Exceptions/UnauthorizedException.cs:44]: Because `RemainingLoginAttempts` is of type `int` 🤔 What would be the c# way to do that elegantly 😄?

Comment (heytherewill) [reply Toggl.Networking/Exceptions/UnauthorizedException.cs:44]: Changing its type to `int?`

Comment (pdrj) [reply Toggl.Networking/Exceptions/UnauthorizedException.cs:44]: Right... 🙈

**Comment by pdrj** [comment]
That's already fixed by @Odrakir in #7393 @dshr

**Comment by pdrj** [comment]
It's just that this part 2 has been done before part 1 on ios has been created ;)
