### PR TITLE
Calendar service

### LINKED ISSUE #2790: Create (and mock) the ICalendarService
Ref #2754 for architectural details
Ref #2755 for API usage details

We need to introduce the `ICalendarService` (this name is encouraged to be improved) interface, allow for it to be registered from the Foundation initialization and mock it in the Foundation layer so that Droid (and iOS for the time being) don't crash, similar to what we're doing with the `PasswordManagerService`.

Tests should be added as applicable.

### PR DESCRIPTION
**Pull request by juanlaube**
## What's this?

Adds a new calendar service that will provide, in the future, all the events for a given date. This is just the interface and a dummy implementation for both Daneel and Giskard, actual connection with the EKEventStore in Daneel will happen in another commit.

### Relationships

Closes #2790
~Depends on #2789, which is not merged for the moment~

## Why do we want this?

We need this to have a common interface to get calendar events.

## How is it done?

It's a new service.

### Why not another way?

We could do things another way and complicate our existence I think 😛 

### Side effects

None.

## Review hints

It's a straightforward review.

## :squid: Permissions

~No u (until #2789 gets merged and I replace `string` with `CalendarItem` in the interface)~
Members of the fellowship of the calendar, you have my permission to merge this.

### CODE REVIEW

File: Toggl.Foundation.MvvmCross/Services/ICalendarService.cs [hunk 1]
```diff
@@ -0,0 +1,11 @@
+﻿using System;
+using System.Collections.Generic;
+
+namespace Toggl.Foundation.MvvmCross.Services
+{
+    public interface ICalendarService
+    {
+        // TODO: Replace `string` with `CalendarItem`
```
Comment (simonrozsival) [inline Toggl.Foundation.MvvmCross/Services/ICalendarService.cs]: Please add a dummy (empty) `CalendarItem` type already in this PR. These comments are ugly.

Comment (willsb) [reply Toggl.Foundation.MvvmCross/Services/ICalendarService.cs]: `//TODO` comments are fine when a PR is WIP, as much as they give everyone the heebie jeebies 😄

Comment (simonrozsival) [reply Toggl.Foundation.MvvmCross/Services/ICalendarService.cs]: 🤦‍♂️ I read the description again and looked into the other PR. Forget what I wrote and pretend it never happened 😆

Comment (juanlaube) [reply Toggl.Foundation.MvvmCross/Services/ICalendarService.cs]: I don't know what comments you're talking about 😄

File: Toggl.Giskard/Toggl.Giskard.csproj [hunk 2]
```diff
@@ -270,8 +271,8 @@
     <Compile Include="Activities\OnboardingActivity.cs" />
     <Compile Include="Activities\LoginActivity.cs" />
     <Compile Include="Activities\LoginActivity.ViewBinds.cs">
-		<DependentUpon>LoginActivity.cs</DependentUpon>
-	</Compile>
+      <DependentUpon>LoginActivity.cs</DependentUpon>
```
Comment (willsb) [inline Toggl.Giskard/Toggl.Giskard.csproj]: Let's just merge this, since it'll keep appearing forever, I guess 😄

File: Toggl.Giskard/Startup/Setup.cs [hunk 3]
```diff
@@ -107,6 +107,7 @@ protected override void InitializeApp(IMvxPluginManager pluginManager, IMvxAppli
                     .WithNavigationService(navigationService)
                     .WithAccessRestrictionStorage(settingsStorage)
                     .WithErrorHandlingService(new ErrorHandlingService(navigationService, settingsStorage))
+                    .WithCalendarService(new CalendarService())
```
Comment (willsb) [inline Toggl.Giskard/Startup/Setup.cs]: Similar to previous PR: Create the extension method for flexibility®
