### PR TITLE
Fix main log header date formatting

### LINKED ISSUE #2347: Date displaying as Day., 28 May seems incorrect
image
 See image for Mon., 28 May both period and comma seem incorrect

### PR DESCRIPTION
**Pull request by juanlaube**
Closes #2347 

🦑 whenever

### CODE REVIEW

File: Toggl.Foundation.MvvmCross/Converters/DateToTitleStringValueConverter.cs [hunk 1]
```diff
@@ -8,6 +8,8 @@ namespace Toggl.Foundation.MvvmCross.Converters
     [Preserve(AllMembers = true)]
     public sealed class DateToTitleStringValueConverter : MvxValueConverter<DateTimeOffset, string>
     {
+        private CultureInfo cultureInfo = CultureInfo.CreateSpecificCulture("en-US");
```
Comment (simonrozsival) [inline Toggl.Foundation.MvvmCross/Converters/DateToTitleStringValueConverter.cs]: This can be readonly.
