### PR TITLE
API exceptions

### LINKED ISSUE #150: Improve API error return value
Right now we are returning pretty useless exceptions with the http content of the response as message.

Soon we will also need _at least_ the http error code, for both the status endpoint, and all other endpoints as well.

### PR DESCRIPTION
**Pull request by simonrozsival**
Closes #150 

This PR includes specific exception classes for different errors of API requests. I also extracted the large switch statement from the `BaseApi.cs` file into a separate helper.

All of these exceptions should be tested, but since this PR already contains too many files, I would suggest putting those tests into a separate PR.

Squash whenever.

### CODE REVIEW

File: Toggl.Ultrawave/Exceptions/ApiErrorResponseException.cs [hunk 1]
```diff
@@ -0,0 +1,16 @@
+﻿using System;
+using System.Net;
+
+namespace Toggl.Ultrawave.Exceptions
+{
+    public class ApiErrorResponseException : ApiException
+    {
+        public readonly HttpStatusCode HttpCode;
```
Comment (willsb) [inline Toggl.Ultrawave/Exceptions/ApiErrorResponseException.cs]: Public fields are a big no 🙅‍♂️ 
Use properties instead.

Though in this case, I'm against exposing/storing the HttpCode altogether.

File: Toggl.Ultrawave/Helpers/ApiExceptions.cs [hunk 2]
```diff
@@ -0,0 +1,52 @@
+﻿using Toggl.Ultrawave.Exceptions;
+using Toggl.Ultrawave.Network;
+
+namespace Toggl.Ultrawave.Helpers
+{
+    class ApiExceptions
```
Comment (willsb) [inline Toggl.Ultrawave/Helpers/ApiExceptions.cs]: Make access modifiers explicit

Comment (willsb) [inline Toggl.Ultrawave/Helpers/ApiExceptions.cs]: Also, this helper method could be in the `ApiErrorResponseException` class, in my opinion

**Comment by simonrozsival** [comment]
I created those exceptions based on a list of API errors of our backend Paul gave me.

File: Toggl.Ultrawave/Helpers/ApiExceptions.cs (hunk 2 above)
Comment (simonrozsival) [inline Toggl.Ultrawave/Helpers/ApiExceptions.cs]: It could be there, I don't like the idea of having a static method inside of an exception class. But if others agree with your suggestion, I can move the code there.

File: Toggl.Ultrawave/Exceptions/ApiErrorResponseException.cs (hunk 1 above)
Comment (simonrozsival) [inline Toggl.Ultrawave/Exceptions/ApiErrorResponseException.cs]: OK, I'll turn that into a property.

There might be a case when the API returns a different status code than we expect. Then this is a catch-it-all case. I could add one more exception, which would be something like `UnknownErrorResponseException` which would hold the HTTP status code and others thus won't have to.

Comment (amulware) [inline Toggl.Ultrawave/Exceptions/ApiErrorResponseException.cs]: I don't want an inherited catch-all class. The base class can and should be used for that in my opinion.

Comment (amulware) [inline Toggl.Ultrawave/Exceptions/ApiErrorResponseException.cs]: And I agree with exposing the status code so that we can handle it separately if needed.

File: Toggl.Ultrawave/Exceptions/TooManyRequestsException.cs [hunk 3]
```diff
@@ -0,0 +1,24 @@
+﻿using System.Net;
+
+namespace Toggl.Ultrawave.Exceptions
+{
+    public sealed class TooManyRequestsException : ClientErrorException
+    {
+        /// <summary>
+        /// HTTP status code 429 "Too Many Redirects" is not included in the System.Net.HttpStatusCode enum.
+        /// </summary>
```
Comment (amulware) [inline Toggl.Ultrawave/Exceptions/TooManyRequestsException.cs]: Remove XML.

File: Toggl.Ultrawave/Helpers/ApiExceptions.cs (hunk 2 above)
Comment (amulware) [inline Toggl.Ultrawave/Helpers/ApiExceptions.cs]: I'm indifferent about where this is and am fine with leaving it here.

File: Toggl.Ultrawave/Exceptions/ApiErrorResponseException.cs (hunk 1 above)
Comment (amulware) [inline Toggl.Ultrawave/Exceptions/ApiErrorResponseException.cs]: Actually, scratch that. (see review below)

File: Toggl.Ultrawave/Exceptions/ForbiddenException.cs [hunk 4]
```diff
@@ -0,0 +1,21 @@
+﻿using System.Net;
+
+namespace Toggl.Ultrawave.Exceptions
+{
+    public sealed class ForbiddenException : ApiErrorResponseException
```
Comment (simonrozsival) [inline Toggl.Ultrawave/Exceptions/ForbiddenException.cs]: Yes, I forgot to change it.

File: Toggl.Ultrawave/Exceptions/ClientErrorException.cs [hunk 5]
```diff
@@ -0,0 +1,12 @@
+﻿using System.Net;
+
+namespace Toggl.Ultrawave.Exceptions
+{
+    public abstract class ClientErrorException : ApiErrorResponseException
+    {
+        protected ClientErrorException(string errorMessage, HttpStatusCode httpCode)
```
Comment (simonrozsival) [inline Toggl.Ultrawave/Exceptions/ClientErrorException.cs]: I don't think this is necessary at runtime as it is an abstract class - you can't instantiate it with some random HTTP status code, It is then up to the classes inheriting from this one.

Comment (simonrozsival) [inline Toggl.Ultrawave/Exceptions/ClientErrorException.cs]: But this is irrelevant - I will create the *unknown error* class and all the other won't store the status code.

**Comment by simonrozsival** [comment]
I think I addressed all your comments.

**Comment by willsb** [comment]
@simonrozsival Please dismiss our reviews when you address all comments, as specified [here](https://github.com/toggl/mobile-docs/blob/develop/pull-request-etiquette.md#making-changes-to-pull-requests)

File: Toggl.Ultrawave/Exceptions/ClientDeprecatedException.cs [hunk 6]
```diff
@@ -0,0 +1,24 @@
+﻿using System.Net;
+
+namespace Toggl.Ultrawave.Exceptions
+{
+    public sealed class ClientDeprecatedException : ClientErrorException
+    {
+        /// <summary>
+        /// HTTP status code 418 "I Am A Teapot" is not included in the System.Net.HttpStatusCode enum.
+        /// </summary>
```
Comment (simonrozsival) [inline Toggl.Ultrawave/Exceptions/ClientDeprecatedException.cs]: I removed them.

File: Toggl.Ultrawave/Exceptions/ServerErrorException.cs [hunk 7]
```diff
@@ -0,0 +1,12 @@
+﻿using System.Net;
+
+namespace Toggl.Ultrawave.Exceptions
+{
+    public abstract class ServerErrorException : ApiErrorResponseException
+    {
+        protected ServerErrorException(string errorMessage, HttpStatusCode httpCode)
```
Comment (simonrozsival) [inline Toggl.Ultrawave/Exceptions/ServerErrorException.cs]: Same as above.

File: Toggl.Ultrawave/Exceptions/TooManyRequestsException.cs (hunk 3 above)
Comment (simonrozsival) [inline Toggl.Ultrawave/Exceptions/TooManyRequestsException.cs]: Removed.

**Comment by simonrozsival** [comment]
Thanks for pointing that out to me, @willsb! I'll read the documentation thoroughly once more.

**Comment by amulware** [comment]
Please also include a note what issue this closes in the PR description as outlined in the docs.

File: Toggl.Ultrawave/Exceptions/ClientErrorException.cs (hunk 5 above)
Comment (amulware) [inline Toggl.Ultrawave/Exceptions/ClientErrorException.cs]: Let's still test (in a future PR is fine) that the correct exception is created for each code. :)

Comment (simonrozsival) [inline Toggl.Ultrawave/Exceptions/ClientErrorException.cs]: I am already working on the tests. I will also create an issue so we don't forget about it.

**Comment by amulware** [comment]
Now, please squash with appropriate emoji, according to the guidelines. :D
