### PR TITLE
🗝 Rename LoginManager into UserAccessManager

### LINKED ISSUE #3884: Rename LoginManager into UserAccessManager
🔑 Related to `user-access-improvements` project.

The LoginManager name is being used, but it is semantically wrong because it is not used only as a login manager, but also for managing signups and logging out. It basically deals with user's access so let's name it `UserAccessManager`.

In addition, since #3878, it also used to log out of the application, instead of directly accessing the datasource to do a database cleanup.

### PR DESCRIPTION
**Pull request by khoi**
## What's this?
 Rename LoginManager into UserAccessManager

### Relationships

Closes #3884

## Why do we want this?
See the issue.

## How is it done?
By renaming duh.

### Side effects
None.

## Review hints
None.

## :squid: Permissions
🦑

### CODE REVIEW

File: Toggl.Foundation.MvvmCross/ViewModels/ForgotPasswordViewModel.cs [hunk 1]
```diff
@@ -21,7 +21,7 @@ namespace Toggl.Foundation.MvvmCross.ViewModels
     public sealed class ForgotPasswordViewModel : MvxViewModel<EmailParameter, EmailParameter>
     {
         private readonly ITimeService timeService;
-        private readonly ILoginManager loginManager;
+        private readonly IUserAccessManager _userAccessManager;
```
Comment (kornelijepetak) [inline Toggl.Foundation.MvvmCross/ViewModels/ForgotPasswordViewModel.cs]: No underscore.

File: Toggl.Foundation.MvvmCross/App.cs [hunk 2]
```diff
@@ -27,28 +27,28 @@ public sealed class AppStart<TFirstViewModelWhenNotLoggedIn> : MvxAppStart
         where TFirstViewModelWhenNotLoggedIn : MvxViewModel
     {
         private readonly ITimeService timeService;
-        private readonly ILoginManager loginManager;
+        private readonly IUserAccessManager _userAccessManager;
```
Comment (kornelijepetak) [inline Toggl.Foundation.MvvmCross/App.cs]: Why underscore here? It's not a preferrable practice in C#.

File: Toggl.Foundation.MvvmCross/ViewModels/LoginViewModel.cs [hunk 3]
```diff
@@ -30,7 +30,7 @@ public enum ShakeTargets
             Password = 2
         }
 
-        private readonly ILoginManager loginManager;
+        private readonly IUserAccessManager _userAccessManager;
```
Comment (kornelijepetak) [inline Toggl.Foundation.MvvmCross/ViewModels/LoginViewModel.cs]: No underscore.

File: Toggl.Foundation.MvvmCross/ViewModels/SignupViewModel.cs [hunk 4]
```diff
@@ -39,7 +39,7 @@ public enum ShakeTargets
         }
 
         private readonly IApiFactory apiFactory;
-        private readonly ILoginManager loginManager;
+        private readonly IUserAccessManager _userAccessManager;
```
Comment (kornelijepetak) [inline Toggl.Foundation.MvvmCross/ViewModels/SignupViewModel.cs]: No underscore.

File: Toggl.Foundation.MvvmCross/ViewModels/TokenResetViewModel.cs [hunk 5]
```diff
@@ -20,7 +20,7 @@ namespace Toggl.Foundation.MvvmCross.ViewModels
     [Preserve(AllMembers = true)]
     public sealed class TokenResetViewModel : MvxViewModel
     {
-        private readonly ILoginManager loginManager;
+        private readonly IUserAccessManager _userAccessManager;
```
Comment (kornelijepetak) [inline Toggl.Foundation.MvvmCross/ViewModels/TokenResetViewModel.cs]: No underscore.

File: Toggl.Foundation.Tests/MvvmCross/ViewModels/LoginViewModelTests.cs [hunk 6]
```diff
@@ -148,28 +148,28 @@ public void ReturnsWhetherThePasswordManagerIsAvailable(bool isAvailable)
         public sealed class TheLoginMethod : LoginViewModelTest
         {
             [Fact, LogIfTooSlow]
-            public void CallsTheLoginManagerWhenTheEmailAndPasswordAreValid()
+            public void CallsTheuserAccessManagerWhenTheEmailAndPasswordAreValid()
```
Comment (kornelijepetak) [inline Toggl.Foundation.Tests/MvvmCross/ViewModels/LoginViewModelTests.cs]:
```suggestion
            public void CallsTheUserAccessManagerWhenTheEmailAndPasswordAreValid()
```

File: Toggl.Foundation.Tests/MvvmCross/ViewModels/LoginViewModelTests.cs [hunk 7]
```diff
@@ -357,29 +357,29 @@ public void TracksTheEventAndException()
         public sealed class TheGoogleLoginMethod : LoginViewModelTest
         {
             [Fact, LogIfTooSlow]
-            public void CallsTheLoginManager()
+            public void CallsTheuserAccessManager()
```
Comment (kornelijepetak) [inline Toggl.Foundation.Tests/MvvmCross/ViewModels/LoginViewModelTests.cs]:
```suggestion
            public void CallsTheUserAccessManager()
```

File: Toggl.Foundation.Tests/MvvmCross/ViewModels/SignupViewModelTests.cs [hunk 8]
```diff
@@ -293,22 +293,22 @@ protected override void AdditionalViewModelSetup()
                 }
 
                 [Fact, LogIfTooSlow]
-                public async Task CallsTheLoginManager()
+                public async Task CallsTheuserAccessManager()
```
Comment (kornelijepetak) [inline Toggl.Foundation.Tests/MvvmCross/ViewModels/SignupViewModelTests.cs]:
```suggestion
                public async Task CallsTheUserAccessManager()
```

File: Toggl.Foundation.Tests/MvvmCross/ViewModels/TokenResetViewModelTests.cs [hunk 9]
```diff
@@ -148,24 +148,24 @@ public async Task DoesNotAttemptToLoginWhileThePasswordIsNotValid()
 
                 TestScheduler.Start();
                 executionObserver.Messages.Last().Value.Kind.Should().Be(NotificationKind.OnError);
-                await LoginManager.DidNotReceive().RefreshToken(Arg.Any<Password>());
+                await UserAccessManager.DidNotReceive().RefreshToken(Arg.Any<Password>());
             }
 
             [Fact, LogIfTooSlow]
-            public async Task CallsTheLoginManagerWhenThePasswordIsValid()
+            public async Task CallsTheuserAccessManagerWhenThePasswordIsValid()
```
Comment (kornelijepetak) [inline Toggl.Foundation.Tests/MvvmCross/ViewModels/TokenResetViewModelTests.cs]:
```suggestion
            public async Task CallsTheUserAccessManagerWhenThePasswordIsValid()
```
