### PR TITLE
Fix reports grouping

### LINKED ISSUE #2327: Ungroup projects in reports legend
Follow up to #1800

We only want projects grouped in the pie chart, not in the legend.

In the legend (list below the pie chart) we want all the projects of the report shown, no matter how small their percentage.

### PR DESCRIPTION
**Pull request by simonrozsival**
Closes #2327 
Ref #2329 

Squash whenever

### CODE REVIEW

File: Toggl.Foundation.MvvmCross/ViewModels/ReportsViewModel.cs [hunk 1]
```diff
@@ -219,7 +224,7 @@ private void onPreferencesChanged(IDatabasePreferences preferences)
         private IReadOnlyList<ChartSegment> groupSegments()
         {
             var otherProjects = segments.Where(segment => segment.Percentage < minimumPieChartSegmentPercentage).ToList();
-            if (otherProjects.Count == 0)
+            if (otherProjects.Count <= 1 || otherProjects.Count == segments.Count)
```
Comment (amulware) [inline Toggl.Foundation.MvvmCross/ViewModels/ReportsViewModel.cs]: If all are <10%, we show them all? We really need to figure out a better rule than the 10% limit...
